version: '3.8'

services:
  # Redis for session storage
  redis:
    image: redis:7-alpine
    container_name: polymarket-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - polymarket-network

  # Session API service
  session-api:
    build:
      context: ../session-api
      dockerfile: Dockerfile
    container_name: polymarket-session-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - SESSION_SECRET=your-super-secret-jwt-signing-key-minimum-256-bits-for-security
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRY=5m
      - REDIS_URL=redis://redis:6379
      - ALLOWED_ORIGINS=http://localhost:3000,http://betting-ui:3000
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - POLYMARKET_API_URL=https://gamma-api.polymarket.com
      - POLYMARKET_WS_URL=wss://stream.polymarket.com
    depends_on:
      - redis
    networks:
      - polymarket-network
    volumes:
      - ../session-api:/app
      - /app/node_modules
    restart: unless-stopped

  # Discord bot service
  discord-bot:
    build:
      context: ../discord-bot
      dockerfile: Dockerfile
    container_name: polymarket-discord-bot
    environment:
      - NODE_ENV=development
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - SESSION_API_URL=http://session-api:3001
      - SESSION_SECRET=your-super-secret-jwt-signing-key-minimum-256-bits-for-security
      - UI_DOMAIN=http://localhost:3000
      - POLYMARKET_API_URL=https://gamma-api.polymarket.com
    depends_on:
      - session-api
    networks:
      - polymarket-network
    volumes:
      - ../discord-bot:/app
      - /app/node_modules
    restart: unless-stopped

  # Next.js betting UI
  betting-ui:
    build:
      context: ../betting-ui
      dockerfile: Dockerfile
    container_name: polymarket-betting-ui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=wss://stream.polymarket.com
      - SESSION_SECRET=your-super-secret-jwt-signing-key-minimum-256-bits-for-security
      - INTERNAL_API_URL=http://session-api:3001
      - NEXT_PUBLIC_POLYMARKET_API_URL=https://gamma-api.polymarket.com
      - POLYMARKET_WS_URL=wss://stream.polymarket.com/markets
    depends_on:
      - session-api
    networks:
      - polymarket-network
    volumes:
      - ../betting-ui:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

networks:
  polymarket-network:
    driver: bridge

volumes:
  redis-data:
    driver: local

# Override for development with hot reload
# Run with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up 